package com.masai.service;

//import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.masai.exception.ApplicationException;
import com.masai.model.User;
import com.masai.repository.UserRepository;

import lombok.extern.slf4j.Slf4j;


@Service
@Slf4j
public class ApplicationServiceInterfaceImplimentation implements ApplicationServiceInterface {
	@Autowired
	private UserRepository uRepo;
	@Override
	public User logInUserDetails(String email) throws Exception{
		log.info("User auth in Service...");
		return uRepo.findByEmail(email).orElseThrow(() -> new ApplicationException("User Not found with Email: "+email));
	}
	@Override
	public User signUpInUser(User user)throws ApplicationException{
		Optional<User> opt = uRepo.findById(user.getUserId());
		if(opt.isPresent() && user.getActive()) {
			throw new ApplicationException("User Already Exists...");
		}
		if(user.getUserId()!=0) {
			throw new ApplicationException("Id is AutoGenerated do not mention it...");
		}
		if(user==null) throw new ApplicationException("Fields should have values...");
		uRepo.save(user);
		return user;
	}
//	@Override
//	public List<User> getAllUser(String name)throws ApplicationException {
//		List<User> users = uRepo.findAll();
//		if(users.size()==0) {
//			new ApplicationException("User Not Found...");
//		}
//		return users;
//	}
	
	
	

}
